<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);NU1903</NoWarn>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\Chemy.Core\Chemy.Core.csproj" />
  </ItemGroup>

</Project>
